a=int(input("enter first number:"))
b=int(input("enter second number:"))
print ("Addition=",a+b)
print ("subtraction=",a-b)
print ("Multiplication=",a*b)
print ("Division=",a/b)
print ("Modulus=",a%b)
